export const ROUTES = {
  CUSTOMER: {
    HOME: '/customer/home',
    SEARCH: '/customer/search',
    CATEGORIES: '/customer/categories',
    OFFERS: '/customer/offers',
    PRODUCT: (id) => `/customer/product/${id}`,
    CART: '/customer/cart',
    CHECKOUT: '/customer/checkout',
    PAYMENT: '/customer/payment',
    ORDER_SUCCESS: '/customer/order-success',
    ORDERS: '/customer/orders',
    TRACKING: (id) => `/customer/track/${id}`,
    PROFILE: '/customer/profile',
    NOTIFICATIONS: '/customer/notifications',
    SIGNIN: '/customer/signin',
    SIGNUP: '/customer/signup',
  },
  ADMIN: {
    SIGNIN: '/admin/signin',
    DASHBOARD: '/admin/dashboard',
    ORDERS: '/admin/orders',
    PRODUCTS: '/admin/products',
    CATEGORIES: '/admin/categories',
    BRANCHES: '/admin/branches',
    CUSTOMERS: '/admin/customers',
    DELIVERY: '/admin/delivery',
    SUPPORT: '/admin/support',
    REPORTS: '/admin/reports',
    NOTIFICATIONS: '/admin/notifications',
  },
  DELIVERY: {
    SIGNIN: '/delivery/signin',
    SIGNUP: '/delivery/signup',
    DASHBOARD: '/delivery/dashboard',
    ORDERS: '/delivery/orders',
    ORDER_DETAILS: (id) => `/delivery/orders/${id}`,
    NAVIGATION: (id) => `/delivery/navigation/${id}`,
    GIGS: '/delivery/gigs',
    WALLET: '/delivery/wallet',
    PROFILE: '/delivery/profile',
    NOTIFICATIONS: '/delivery/notifications',
  },
  SUPPORT: {
    SIGNIN: '/support/signin',
    DASHBOARD: '/support/dashboard',
    ORDERS: '/support/orders',
    PRODUCTS: '/support/products',
    ISSUES: '/support/issues',
    AGENTS: '/support/agents',
    NOTIFICATIONS: '/support/notifications',
  },
};
