import { useState } from 'react'
import { useLocation } from 'react-router-dom'
import { Package, Boxes, Headphones, BarChart3, Plus, CheckCircle2 } from 'lucide-react'
import { usePrototypeContext } from '../../context/PrototypeContext'
import { addProduct, toggleProductAvailability, updateOrderStatus, addIssue, updateIssue } from '../../services/prototypeStore'
import { NotificationPanel } from '../../components/notifications/NotificationPanel'

export function SupportPage(){const {pathname}=useLocation();const path=pathname.replace('/support/','')||'dashboard';const {orders,products,issues=[],notifications}=usePrototypeContext();const title={dashboard:'Support Overview',orders:'Incoming Orders',products:'Product Management',issues:'Customer Issues',notifications:'Notifications'}[path]||'Support';return <section><div className="dashboard-top"><div><span className="eyebrow">GOLDEN FOOD BOWL</span><h1>{title}</h1></div><button>Support Agent ▾</button></div>{path==='dashboard'&&<Dashboard orders={orders} products={products} issues={issues}/>} {path==='products'&&<Products products={products}/>} {path==='orders'&&<Orders orders={orders}/>} {path==='issues'&&<Issues issues={issues}/>} {path==='notifications'&&<NotificationPanel notifications={notifications} role="support"/>}</section>}
function Dashboard({orders,products,issues}){return <><div className="admin-stats"><div><Package/><strong>{orders.length}</strong><span>Incoming orders</span></div><div><Boxes/><strong>{products.length}</strong><span>Products</span></div><div><Headphones/><strong>{issues.filter(i=>i.status==='OPEN').length}</strong><span>Open issues</span></div><div><BarChart3/><strong>94%</strong><span>Resolved today</span></div></div><Orders orders={orders}/></>}
function Products({products}){const [name,setName]=useState('');const [price,setPrice]=useState('');const add=()=>{if(!name.trim()||!price)return;addProduct({name,price:Number(price),category:'bowls',calories:400,portion:'350g',image:'🍲',description:'New menu item',ingredients:['Fresh ingredients']});setName('');setPrice('')};return <div className="admin-table-card"><div className="table-heading"><h2>Menu Products</h2><div><input value={name} onChange={e=>setName(e.target.value)} placeholder="Product name"/><input value={price} onChange={e=>setPrice(e.target.value)} placeholder="Price" type="number"/><button onClick={add}><Plus size={15}/> Add</button></div></div><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Availability</th><th>Action</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><strong>{p.image} {p.name}</strong></td><td>{p.category}</td><td>₹{p.price}</td><td><span className="table-status">{p.available?'Available':'Unavailable'}</span></td><td><button onClick={()=>toggleProductAvailability(p.id)}>{p.available?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div>}
function Orders({orders}){return <div className="admin-table-card"><div className="table-heading"><h2>Orders Requiring Attention</h2><span>{orders.length} orders</span></div><table><thead><tr>{['Reference','Customer','Branch','Amount','Status','Action'].map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><strong>#{o.id}</strong></td><td>{o.customer}</td><td>{o.branch}</td><td>₹{o.total}</td><td><span className="table-status">{o.status.replaceAll('_',' ')}</span></td><td><button onClick={()=>updateOrderStatus(o.id,o.status==='CONFIRMED'?'PREPARING':o.status==='PREPARING'?'READY_FOR_PICKUP':o.status)}>Update</button></td></tr>)}</tbody></table></div>}
function Issues({issues}){const [customer,setCustomer]=useState('');const [message,setMessage]=useState('');const create=()=>{if(!customer||!message)return;addIssue({customer,message,priority:'Medium'});setCustomer('');setMessage('')};return <><div className="admin-table-card"><div className="table-heading"><h2>Log Customer Issue</h2><button onClick={create}><Plus size={15}/> Create</button></div><div className="support-issue-form"><input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Customer name"/><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Issue description"/></div></div><div className="admin-table-card"><div className="table-heading"><h2>Open Issues</h2></div><table><thead><tr><th>Customer</th><th>Issue</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody>{issues.length?issues.map(i=><tr key={i.id}><td>{i.customer}</td><td>{i.message}</td><td>{i.priority}</td><td>{i.status}</td><td><button onClick={()=>updateIssue(i.id,'RESOLVED')}><CheckCircle2 size={15}/> Resolve</button></td></tr>):<tr><td colSpan="5">No customer issues yet.</td></tr>}</tbody></table></div></>}
